import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class AgencyBase(BaseModel):
    name: str


class AgencyCreate(AgencyBase):
    pass


class AgencyOut(AgencyBase):
    id: uuid.UUID
    owner_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AgencyClientBase(BaseModel):
    client_name: str
    account_manager_id: uuid.UUID | None = None


class AgencyClientCreate(AgencyClientBase):
    # account_id might be provided or auto-generated by the service
    account_id: uuid.UUID | None = None


class AgencyClientOut(AgencyClientBase):
    id: uuid.UUID
    agency_id: uuid.UUID
    account_id: uuid.UUID
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AgencyTeamMemberBase(BaseModel):
    role: str = Field(default="CONTENT_CREATOR")


class AgencyTeamMemberCreate(AgencyTeamMemberBase):
    user_id: uuid.UUID


class AgencyTeamMemberOut(AgencyTeamMemberBase):
    id: uuid.UUID
    agency_id: uuid.UUID
    user_id: uuid.UUID
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class WhiteLabelConfigBase(BaseModel):
    custom_domain: str | None = None
    portal_name: str = "Client Portal"
    logo_url: str | None = None
    primary_color: str | None = None
    secondary_color: str | None = None


class WhiteLabelConfigUpdate(WhiteLabelConfigBase):
    pass


class WhiteLabelConfigOut(WhiteLabelConfigBase):
    id: uuid.UUID
    agency_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)
