"""social post versions table (Slice 5 GRX-SOCIAL-007)

Revision ID: 1cdd976bbe4e
Revises: 51ab72730a68
Create Date: 2026-08-12 14:35:39.017413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1cdd976bbe4e"
down_revision: str | Sequence[str] | None = "51ab72730a68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_post_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("social_post_id", sa.UUID(), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("media_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ig_media_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["social_post_id"],
            ["social_posts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_social_post_versions_account_id"),
        "social_post_versions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "ix_social_post_versions_social_post_id",
        "social_post_versions",
        ["social_post_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_social_post_versions_social_post_id", table_name="social_post_versions")
    op.drop_index(op.f("ix_social_post_versions_account_id"), table_name="social_post_versions")
    op.drop_table("social_post_versions")
    # ### end Alembic commands ###
