"""social posts and media tables (Slice 5 GRX-SOCIAL-004)

Revision ID: 51ab72730a68
Revises: 117ce471bf00
Create Date: 2026-08-12 14:17:30.938219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51ab72730a68"
down_revision: str | Sequence[str] | None = "117ce471bf00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("social_connection_id", sa.UUID(), nullable=False),
        sa.Column("caption", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("ig_media_id", sa.Text(), nullable=True),
        sa.Column("ig_permalink", sa.Text(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ("
            "'DRAFT', 'SCHEDULED', 'DISPATCHING', 'PUBLISHING', 'PUBLISHED', "
            "'CANCELLED', 'FAILED'"
            ")",
            name="ck_social_posts_status",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["social_connection_id"],
            ["social_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_social_posts_account_id"), "social_posts", ["account_id"], unique=False
    )
    op.create_index(
        "ix_social_posts_status_scheduled_at",
        "social_posts",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "social_post_media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("social_post_id", sa.UUID(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("public_url", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("media_type IN ('IMAGE')", name="ck_social_post_media_media_type"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["social_post_id"], ["social_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_social_post_media_account_id"), "social_post_media", ["account_id"], unique=False
    )
    op.create_index(
        "ix_social_post_media_social_post_id", "social_post_media", ["social_post_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_social_post_media_social_post_id", table_name="social_post_media")
    op.drop_index(op.f("ix_social_post_media_account_id"), table_name="social_post_media")
    op.drop_table("social_post_media")
    op.drop_index("ix_social_posts_status_scheduled_at", table_name="social_posts")
    op.drop_index(op.f("ix_social_posts_account_id"), table_name="social_posts")
    op.drop_table("social_posts")
    # ### end Alembic commands ###
