"""consent and suppression

Revision ID: 97642610fb46
Revises: b11cffc2cbcf
Create Date: 2026-07-31 19:32:35.249569

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "97642610fb46"
down_revision: str | Sequence[str] | None = "b11cffc2cbcf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="UNKNOWN", nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("recorded_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel IN ('EMAIL', 'SMS')", name="ck_consent_records_channel"),
        sa.CheckConstraint(
            "status IN ('GRANTED', 'WITHDRAWN', 'UNKNOWN')", name="ck_consent_records_status"
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_records_contact_id"), "consent_records", ["contact_id"], unique=False
    )
    op.create_table(
        "suppression_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("suppressed_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "suppressed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('UNSUBSCRIBED', 'BOUNCED', 'COMPLAINED', 'MANUAL')",
            name="ck_suppression_entries_reason",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suppressed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suppression_entries")
    op.drop_index(op.f("ix_consent_records_contact_id"), table_name="consent_records")
    op.drop_table("consent_records")
    # ### end Alembic commands ###
