"""Add phase 6 to 9 models

Revision ID: 99af1457f402
Revises: f5a6b7c8d9e0
Create Date: 2026-09-17 11:13:59.100759

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99af1457f402'
down_revision: str | Sequence[str] | None = 'f5a6b7c8d9e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metrics_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('CAMPAIGN', 'SOCIAL_POST', 'CRM', 'CHANNEL')", name='ck_metric_snapshots_entity_type'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_metric_snapshots_entity_date', 'metric_snapshots', ['account_id', 'entity_type', 'entity_id', 'date'], unique=True)
    op.create_table('raw_provider_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_provider_events_account_id'), 'raw_provider_events', ['account_id'], unique=False)
    op.create_index('ix_raw_provider_events_account_provider', 'raw_provider_events', ['account_id', 'provider'], unique=False)
    op.create_index('ix_raw_provider_events_created_at', 'raw_provider_events', ['created_at'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('recipient_emails', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("frequency IN ('DAILY', 'WEEKLY', 'MONTHLY')", name='ck_scheduled_reports_frequency'),
    sa.CheckConstraint("report_type IN ('CLIENT', 'CHANNEL', 'CAMPAIGN', 'ACCOUNT_OVERVIEW')", name='ck_scheduled_reports_report_type'),
    sa.CheckConstraint("status IN ('ACTIVE', 'PAUSED')", name='ck_scheduled_reports_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reports_account_id'), 'scheduled_reports', ['account_id'], unique=False)
    op.create_index('ix_scheduled_reports_next_run_at', 'scheduled_reports', ['next_run_at'], unique=False)
    op.create_table('sms_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), server_default='TWILIO', nullable=False),
    sa.Column('account_sid', sa.Text(), nullable=False),
    sa.Column('auth_token_encrypted', sa.Text(), nullable=False),
    sa.Column('sender_number', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('TWILIO')", name='ck_sms_connections_provider'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_connections_account_id'), 'sms_connections', ['account_id'], unique=False)
    op.create_table('whatsapp_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('waba_id', sa.Text(), nullable=False),
    sa.Column('phone_number_id', sa.Text(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_verify_token_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_connections_account_id'), 'whatsapp_connections', ['account_id'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='PENDING', nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('APPROVED', 'PENDING', 'REJECTED')", name='ck_whatsapp_templates_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agency_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('account_manager_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['account_manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_agency_clients_account_id', 'agency_clients', ['account_id'], unique=True)
    op.create_table('agency_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), server_default='CONTENT_CREATOR', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'ACCOUNT_MANAGER', 'CONTENT_CREATOR')", name='ck_agency_team_members_role'),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_agency_team_members_user_agency', 'agency_team_members', ['agency_id', 'user_id'], unique=True)
    op.create_table('sms_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('recipient_type', sa.Text(), nullable=False),
    sa.Column('recipient_segment_id', sa.UUID(), nullable=True),
    sa.Column('recipient_list_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='DRAFT', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'SCHEDULED', 'DISPATCHING', 'SENDING', 'SENT', 'CANCELLED', 'FAILED')", name='ck_sms_campaigns_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['recipient_segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_sms_campaigns_account_id'), 'sms_campaigns', ['account_id'], unique=False)
    op.create_index('ix_sms_campaigns_status_scheduled_at', 'sms_campaigns', ['status', 'scheduled_at'], unique=False)
    op.create_table('whatsapp_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('recipient_type', sa.Text(), nullable=False),
    sa.Column('recipient_segment_id', sa.UUID(), nullable=True),
    sa.Column('recipient_list_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='DRAFT', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'SCHEDULED', 'DISPATCHING', 'SENDING', 'SENT', 'CANCELLED', 'FAILED')", name='ck_whatsapp_campaigns_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['recipient_segment_id'], ['segments.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_whatsapp_campaigns_account_id'), 'whatsapp_campaigns', ['account_id'], unique=False)
    op.create_index('ix_whatsapp_campaigns_status_scheduled_at', 'whatsapp_campaigns', ['status', 'scheduled_at'], unique=False)
    op.create_table('white_label_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('custom_domain', sa.Text(), nullable=True),
    sa.Column('portal_name', sa.Text(), server_default='Client Portal', nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.Text(), nullable=True),
    sa.Column('secondary_color', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id'),
    sa.UniqueConstraint('custom_domain')
    )
    op.create_table('inbox_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('channel_identity_id', sa.Text(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('WHATSAPP', 'IG_DM', 'FB_COMMENT', 'EMAIL', 'TWITTER_DM')", name='ck_inbox_conversations_channel'),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'SNOOZED')", name='ck_inbox_conversations_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_conversations_account_id'), 'inbox_conversations', ['account_id'], unique=False)
    op.create_index('ix_inbox_conversations_account_status', 'inbox_conversations', ['account_id', 'status'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('INBOUND', 'OUTBOUND')", name='ck_inbox_messages_direction'),
    sa.ForeignKeyConstraint(['conversation_id'], ['inbox_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbox_messages_conversation_id', 'inbox_messages', ['conversation_id'], unique=False)
    op.add_column('account_subscriptions', sa.Column('stripe_customer_id', sa.Text(), nullable=True))
    op.add_column('account_subscriptions', sa.Column('stripe_subscription_id', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'account_subscriptions', ['razorpay_subscription_id'])
    op.create_unique_constraint(None, 'account_subscriptions', ['stripe_subscription_id'])
    op.add_column('contacts', sa.Column('whatsapp_opt_out', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('contacts', sa.Column('sms_opt_out', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('social_post_media', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('subscription_plans', sa.Column('stripe_product_id', sa.Text(), nullable=True))
    op.add_column('subscription_plans', sa.Column('stripe_price_id_usd', sa.Text(), nullable=True))
    op.add_column('subscription_plans', sa.Column('stripe_price_id_inr', sa.Text(), nullable=True))
    op.drop_constraint(op.f('suppression_entries_suppressed_by_user_id_fkey'), 'suppression_entries', type_='foreignkey')
    op.drop_constraint(op.f('suppression_entries_contact_id_fkey'), 'suppression_entries', type_='foreignkey')
    op.create_foreign_key(None, 'suppression_entries', 'users', ['suppressed_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'suppression_entries', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppression_entries', type_='foreignkey')
    op.drop_constraint(None, 'suppression_entries', type_='foreignkey')
    op.create_foreign_key(op.f('suppression_entries_contact_id_fkey'), 'suppression_entries', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(op.f('suppression_entries_suppressed_by_user_id_fkey'), 'suppression_entries', 'users', ['suppressed_by_user_id'], ['id'])
    op.drop_column('subscription_plans', 'stripe_price_id_inr')
    op.drop_column('subscription_plans', 'stripe_price_id_usd')
    op.drop_column('subscription_plans', 'stripe_product_id')
    op.alter_column('social_post_media', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_column('contacts', 'sms_opt_out')
    op.drop_column('contacts', 'whatsapp_opt_out')
    op.drop_constraint(None, 'account_subscriptions', type_='unique')
    op.drop_constraint(None, 'account_subscriptions', type_='unique')
    op.drop_column('account_subscriptions', 'stripe_subscription_id')
    op.drop_column('account_subscriptions', 'stripe_customer_id')
    op.drop_index('ix_inbox_messages_conversation_id', table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index('ix_inbox_conversations_account_status', table_name='inbox_conversations')
    op.drop_index(op.f('ix_inbox_conversations_account_id'), table_name='inbox_conversations')
    op.drop_table('inbox_conversations')
    op.drop_table('white_label_configs')
    op.drop_index('ix_whatsapp_campaigns_status_scheduled_at', table_name='whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_campaigns_account_id'), table_name='whatsapp_campaigns')
    op.drop_table('whatsapp_campaigns')
    op.drop_index('ix_sms_campaigns_status_scheduled_at', table_name='sms_campaigns')
    op.drop_index(op.f('ix_sms_campaigns_account_id'), table_name='sms_campaigns')
    op.drop_table('sms_campaigns')
    op.drop_index('ux_agency_team_members_user_agency', table_name='agency_team_members')
    op.drop_table('agency_team_members')
    op.drop_index('ux_agency_clients_account_id', table_name='agency_clients')
    op.drop_table('agency_clients')
    op.drop_table('agencies')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_connections_account_id'), table_name='whatsapp_connections')
    op.drop_table('whatsapp_connections')
    op.drop_index(op.f('ix_sms_connections_account_id'), table_name='sms_connections')
    op.drop_table('sms_connections')
    op.drop_index('ix_scheduled_reports_next_run_at', table_name='scheduled_reports')
    op.drop_index(op.f('ix_scheduled_reports_account_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index('ix_raw_provider_events_created_at', table_name='raw_provider_events')
    op.drop_index('ix_raw_provider_events_account_provider', table_name='raw_provider_events')
    op.drop_index(op.f('ix_raw_provider_events_account_id'), table_name='raw_provider_events')
    op.drop_table('raw_provider_events')
    op.drop_index('ux_metric_snapshots_entity_date', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
