"""users roles permissions schema

Revision ID: d330e8b64b48
Revises: 9ca09405a2b3
Create Date: 2026-07-24 21:25:14.613902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d330e8b64b48"
down_revision: str | Sequence[str] | None = "9ca09405a2b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Fixed (not autogenerated-per-run) seed UUIDs, per RBAC.md's Sprint 1 role/permission set —
# fixed so this migration is reproducible and role_permissions rows can reference them
# directly without a round-trip query.
ROLE_SUPER_ADMIN = "f654ec88-ba59-4cd2-a74a-032cec74c422"
ROLE_ADMIN = "8c7ebd1a-f1fe-4d22-bb7f-29c79d0444ce"
ROLE_MARKETING_MANAGER = "6b7dc157-82c4-4878-b12d-826b67cf7181"
ROLE_CONTENT_CREATOR = "03c1c2a9-1315-4a86-93eb-b5c936280372"
ROLE_ANALYST = "6ab3fff0-9fcb-46e0-9cdb-0c54c7032ab3"
ROLE_VIEWER = "cd7ad750-9044-4ee8-919d-9b6a8d2f27ec"

PERM_USERS_MANAGE = "350eb58e-e5db-4e15-883b-92eb7ab8fd63"
PERM_ROLES_MANAGE = "f6f58913-494d-4bf5-9aae-815d76fda02c"
PERM_COMPANY_EDIT = "86efdff1-b043-46e5-b9b4-ae509a4fde90"
PERM_COMPANY_VIEW = "70eb0cce-f314-41eb-9843-095c68ace80e"
PERM_AUDIT_VIEW = "0e4f2bd5-ff7d-4873-b0ef-d71410303902"
PERM_ADMIN_ACCESS = "b3c1315c-bc23-4f6c-a81e-bfec1a24149a"


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED')", name="ck_users_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("assigned_by_user_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###

    _seed_rbac_data()


def _seed_rbac_data() -> None:
    """Sprint 1 roles, permission codes, and role->permission matrix — see RBAC.md."""
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.Text()),
        sa.column("description", sa.Text()),
    )
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.Text()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    op.bulk_insert(
        roles_table,
        [
            {
                "id": ROLE_SUPER_ADMIN,
                "name": "Super Admin",
                "description": "Full access, incl. integrations, credentials, user management",
            },
            {
                "id": ROLE_ADMIN,
                "name": "Admin",
                "description": "User management, company settings, most operational access",
            },
            {
                "id": ROLE_MARKETING_MANAGER,
                "name": "Marketing Manager",
                "description": "Campaigns, segments, social, analytics — approval authority",
            },
            {
                "id": ROLE_CONTENT_CREATOR,
                "name": "Content Creator",
                "description": "Drafts, AI generation, media — no send/publish authority",
            },
            {
                "id": ROLE_ANALYST,
                "name": "Analyst",
                "description": "Read-only analytics and reporting",
            },
            {
                "id": ROLE_VIEWER,
                "name": "Viewer",
                "description": "Read-only, broadest restriction",
            },
        ],
    )

    op.bulk_insert(
        permissions_table,
        [
            {
                "id": PERM_USERS_MANAGE,
                "code": "users.manage",
                "description": "Create/invite/disable users, assign roles",
            },
            {
                "id": PERM_ROLES_MANAGE,
                "code": "roles.manage",
                "description": "View role/permission assignments",
            },
            {
                "id": PERM_COMPANY_EDIT,
                "code": "company.settings.edit",
                "description": "Edit company profile and brand settings",
            },
            {
                "id": PERM_COMPANY_VIEW,
                "code": "company.settings.view",
                "description": "View company profile and brand settings",
            },
            {
                "id": PERM_AUDIT_VIEW,
                "code": "audit.view",
                "description": "View audit log",
            },
            {
                "id": PERM_ADMIN_ACCESS,
                "code": "admin.access",
                "description": "Access the admin dashboard shell",
            },
        ],
    )

    # Sprint 1 role -> permission matrix, per RBAC.md.
    all_roles = (
        ROLE_SUPER_ADMIN,
        ROLE_ADMIN,
        ROLE_MARKETING_MANAGER,
        ROLE_CONTENT_CREATOR,
        ROLE_ANALYST,
        ROLE_VIEWER,
    )
    admin_only_roles = (ROLE_SUPER_ADMIN, ROLE_ADMIN)
    matrix: dict[str, tuple[str, ...]] = {
        PERM_USERS_MANAGE: admin_only_roles,
        PERM_ROLES_MANAGE: admin_only_roles,
        PERM_COMPANY_EDIT: admin_only_roles,
        PERM_COMPANY_VIEW: all_roles,
        PERM_AUDIT_VIEW: admin_only_roles,
        PERM_ADMIN_ACCESS: admin_only_roles,
    }

    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_id, "permission_id": permission_id}
            for permission_id, role_ids in matrix.items()
            for role_id in role_ids
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("permissions")
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS citext")
