name: deploy-prod

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend-huggingface.yml
    secrets: inherit

  deploy-frontend:
    uses: ./.github/workflows/deploy-frontend-netlify.yml
    secrets: inherit
